"""Pydantic request and response models for the Garmin HTTP API."""

from typing import Any

from pydantic import BaseModel, Field


class AccountCreateRequest(BaseModel):
    email: str = Field(
        min_length=3,
        description="Garmin Connect account email.",
        examples=["person@example.com"],
    )
    password: str = Field(
        min_length=1,
        description="Garmin Connect account password.",
        examples=["garmin-password"],
    )
    label: str | None = Field(
        default=None,
        description="Optional internal label for this Garmin account.",
        examples=["Samuel"],
    )
    is_cn: bool = Field(
        default=False,
        description="Use the Garmin China login flow when the account is CN-based.",
    )


class AccountCreateResponse(BaseModel):
    account_id: str = Field(description="Internal account id generated by the API.")
    api_key: str = Field(
        description=(
            "Secret account API key. Store it now; only its SHA-256 hash is persisted."
        )
    )
    mfa_required: bool = Field(
        default=False,
        description="Whether Garmin requested MFA for the first login.",
    )
    message: str = Field(description="Human-readable next step.")


class MfaRequest(BaseModel):
    mfa_code: str = Field(
        min_length=3,
        description="One-time MFA code received from Garmin.",
        examples=["123456"],
    )


class AccountStatusResponse(BaseModel):
    account_id: str = Field(description="Internal account id.")
    label: str | None = Field(description="Optional internal account label.")
    authenticated: bool = Field(description="True when Garmin login/token refresh works.")


class DataResponse(BaseModel):
    account_id: str = Field(description="Internal account id.")
    data: Any = Field(
        description=(
            "Raw Garmin payload returned by the underlying garminconnect method. "
            "Keys vary by endpoint and Garmin account/device capabilities."
        )
    )
    cached: bool = Field(
        default=False,
        description="True when the response came from the short in-memory cache.",
    )


class DailyReportResponse(BaseModel):
    account_id: str = Field(description="Internal account id.")
    date: str = Field(description="Report date in YYYY-MM-DD format.")
    cached: bool = Field(
        default=False,
        description="True when the full report came from the in-memory cache.",
    )
    summary: Any | None = Field(
        default=None,
        description=(
            "Daily Garmin summary with calories, steps, distance, active minutes "
            "and other all-day totals when available."
        ),
    )
    health: dict[str, Any | None] = Field(
        description=(
            "Health sections keyed by metric name: heart_rate, sleep, hrv, "
            "body_battery, body_battery_events, stress, respiration, spo2, "
            "hydration, intensity_minutes and resting_heart_rate."
        )
    )
    training: dict[str, Any | None] = Field(
        description=(
            "Training sections keyed by metric name: training_readiness, "
            "training_status, max_metrics, fitness_age and recent_activities."
        )
    )
    body: dict[str, Any | None] = Field(
        description=(
            "Body composition, weigh-in and blood-pressure sections when available."
        )
    )
    nutrition: dict[str, Any | None] = Field(
        description=(
            "Nutrition sections from Garmin Connect+ when available: food_log, "
            "meals and settings."
        )
    )
    warnings: list[str] = Field(
        default_factory=list,
        description=(
            "Non-fatal section failures, for example nutrition unavailable on the "
            "account or a Garmin endpoint returning no data."
        ),
    )


class FoodPhotoAnalysisResponse(BaseModel):
    account_id: str = Field(description="Internal account id.")
    status: str = Field(
        description="Current status of this endpoint.",
        examples=["unsupported"],
    )
    message: str = Field(description="Human-readable explanation.")
    garmin_connect_plus_feature: bool = Field(
        description=(
            "True because Garmin documents photo/AI food logging as a "
            "Garmin Connect+ app feature."
        )
    )
    filename: str | None = Field(description="Uploaded filename.")
    content_type: str | None = Field(description="Uploaded content type.")
    meal_type: str | None = Field(description="Optional meal type sent by the client.")
    notes: str | None = Field(description="Optional notes sent by the client.")
    next_steps: list[str] = Field(
        description="Implementation notes before this can return real nutrition feedback."
    )
